---

- hosts: imobso
  remote_user: root
  roles:
    - bootstrap
    - nginx
    - openbazaar
    - nodejs
  vars_files:
    - vars/secret.yml
  vars:
    nginx_user: www-data
    nginx_default_release: ""
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: myopenbazaar.top www.myopenbazaar.top
        return: 301 https://$host$request_uri

      - listen: 443 ssl default_server
        server_name: myopenbazaar.top www.myopenbazaar.top
        root: /var/www/myopenbazaar.top
        index: index.html index.htm

        extra_parameters: |
          ssl_certificate       /etc/letsencrypt/live/myopenbazaar.top/fullchain.pem;
          ssl_certificate_key   /etc/letsencrypt/live/myopenbazaar.top/privkey.pem;
          location / {
            try_files $uri $uri/ @api;
          }
          location @api {
            proxy_pass            http://127.0.0.1:5000/;
            proxy_redirect        off;
            proxy_buffering       off;
            proxy_set_header      X-Real-IP $remote_addr;
            proxy_set_header      X-Scheme $scheme;
            proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header      Host $http_host;
          }

    openbazaar_git_url: https://github.com/OpenBazaar/OpenBazaar-Server.git
    openbazaar_git_version: 11b492ef1f397d2d465506be2cfc1d812e98a2d0
    openbazaar_port: 18469
    openbazaar_proto: http
    openbazaar_host: 127.0.0.1
    openbazaar_username: "{{ vault_openbazaar_username }}"
    openbazaar_password: "{{ vault_openbazaar_password }}"
    openbazaar_allowed_ip: "{{ vault_openbazaar_allowed_ip }}"
    openbazaar_additional_flags: ""


    letsencrypt_webroot_path: /var/www/myopenbazaar.top
    letsencrypt_email: "{{ vault_admin_email }}"
    letsencrypt_cert_domains:
      - myopenbazaar.top
    letsencrypt_renewal_command_args: '--renew-hook "service restart nginx"'


  tasks:
    - name: clone app repo to server
      git: track_submodules=yes force=yes repo=https://github.com/insanity54/imobso.git dest=/tmp/imobso/source

    - name: create app group
      group: name=imobso state=present

    - name: create app user
      user: name=imobso shell=/bin/bash

    # - name: set up system environment variables
    #   tags: env
    #   template: src=system-env.j2 dest=/etc/profile.d/imobso.sh owner=root group=root mode=0755

    - name: create folder for node
      file: state=directory path=/var/node/imobso owner=imobso owner=imobso group=imobso mode=0644

    - name: create folder for nginx
      file: state=directory path=/var/www/myopenbazaar.top owner=www-data group=www-data mode=0755

      # @todo switch to copy module once https://github.com/ansible/ansible-modules-core/issues/2875 is closed
    - name: copy client/dist files to nginx dir
      command: creates=/var/www/myopenbazaar.top/index.html cp -a /tmp/imobso/source/client/dist/. /var/www/myopenbazaar.top

    - name: set permissions for client/dist files
      file: path=/var/www/myopenbazaar.top/ owner=www-data group=www-data mode=0755 recurse=true
      notify:
        - reload nginx

    - name: copy node app to its place
      command: cp -a /tmp/imobso/source/. /var/node/imobso
      args:
        creates: /var/node/imobso/package.json

    - name: install node app
      npm: path=/var/node/imobso

    - name: set node app permissions
      file: path=/var/node/ owner=imobso group=imobso mode=744 recurse=true

    - name: create node app environment variables file
      template: src=app-env.j2 dest=/var/node/imobso/.env owner=imobso group=imobso mode=0600

    - name: create app upstart script
      command: nf export --app imobso --user imobso --gid imobso --out /etc/init
      args:
        creates: /etc/init/imobso.conf
        chdir: /var/node/imobso
      notify: restart app


  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded

    - name: restart openbazaar
      service: name=openbazaard state=restarted

    - name: restart app
      service: name=imobso state=restarted
