---

- hosts: imobso
  remote_user: root
  roles:
    - bootstrap
    - nginx
    - openbazaar
    - nodejs
  vars_files:
    - vars/secret.yml
  vars:
    nginx_sites:
     - server:
        file_name: imobso.teamrpc.info
        listen: 80
        server_name: imobso.teamrpc.info
        location1:
          name: /
          try_files: "$uri $uri/ /index.html"

        location2:
          name: /v1/
            proxy_pass: "http://127.0.0.1:5000/"
            proxy_redirect:  'off'
            proxy_set_header: 'Host $host'
            proxy_set_header: 'X-Real-IP $remote_addr'
            proxy_set_header: 'X-Forwarded-For $proxy_add_x_forwarded_for'

    openbazaar_git_url: https://github.com/OpenBazaar/OpenBazaar-Server.git
    openbazaar_git_version: 11b492ef1f397d2d465506be2cfc1d812e98a2d0
    openbazaar_username: "{{ vault_openbazaar_username }}"
    openbazaar_password: "{{ vault_openbazaar_password }}"
    openbazaar_allowed_ip: "{{ vault_openbazaar_allowed_ip }}"
    openbazaar_additional_flags: ""

  tasks:
    - name: 
