---

- hosts: imobso
  remote_user: root
  roles:
    - letsencrypt
  vars_files:
    - vars/secret.yml
  vars:
    letsencrypt_webroot_path: /var/www/myopenbazaar.top
    letsencrypt_email: "{{ vault_admin_email }}"
    letsencrypt_cert_domains:
      - myopenbazaar.top
    letsencrypt_renewal_command_args: '--renew-hook "service restart nginx"'
